Compile MFEM externally (#550)

diff --git a/.github/actions/setup-runner/action.yml b/.github/actions/setup-runner/action.yml
--- a/.github/actions/setup-runner/action.yml
+++ b/.github/actions/setup-runner/action.yml
@@ -102,6 +102,26 @@ runs:
         echo "$(realpath spack/bin)" >> "$GITHUB_PATH"
         echo "SPACK_DISABLE_LOCAL_CONFIG=1" >> "$GITHUB_ENV"
         echo "SPACK_COLOR=always" >> "$GITHUB_ENV"
+
+    - name: Patch Spack package.py files for known problems
+      shell: bash
+      run: |
+        PALACE_DIR=$PWD
+        cd $(spack location --repo builtin)
+        for patch in "$PALACE_DIR"/spack_repo/patches/*.diff; do
+          if [ -f "$patch" ]; then
+            if ! git apply --check "$patch" 2>/dev/null; then
+              echo "Cannot apply $patch (PR may have already been merged)"
+              echo "Please remove $patch from the Palace repo if the PR was merged"
+            else
+              echo "Applying patch: $patch"
+              git apply "$patch"
+            fi
+          fi
+        done
+
+        # Workaround for https://github.com/spack/spack/issues/51505
+        ln -s "$(spack location --repo builtin)"/packages/mfem "$PALACE_DIR"/spack_repo/local/packages/
         
     - name: Install Julia
       id: setup-julia
diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -36,18 +36,39 @@ jobs:
           buildcache: true
           color: true
 
+          
+      - name: Patch Spack package.pys for known problems
+        shell: bash
+        run: |
+          PALACE_DIR=$PWD
+          cd $(spack location --repo builtin)
+          for patch in "$PALACE_DIR"/spack_repo/patches/*.diff; do
+            if [ -f "$patch" ]; then
+              if ! git apply --check "$patch" 2>/dev/null; then
+                echo "Cannot apply $patch (PR may have already been merged)"
+                echo "Please remove $patch from the Palace repo if the PR was merged"
+              else
+                echo "Applying patch: $patch"
+                git apply "$patch"
+              fi
+            fi
+          done
+  
+          # Workaround for https://github.com/spack/spack/issues/51505
+          ln -s "$(spack location --repo builtin)"/packages/mfem "$PALACE_DIR"/spack_repo/local/packages/
+  
       - name: Setup Environment
         run: |
           # Spack.yaml with most / all settings configured
           cat << EOF > spack.yaml
           spack:
             specs:
-              - palace # we install this without a cache each time
+              - local.palace@develop # we install this without a cache each time
             view: false
             config:
               install_tree:
                 root: /opt/spack
-                padded_length: False
+                padded_length: false
             concretizer:
               reuse: false
               unify: true
@@ -113,7 +134,15 @@ jobs:
         run: |
           spack -e . install --only-concrete --show-log-on-error --only package --keep-stage --no-cache
         # If you want to use the branch-local source instead (should we always do this?)
-        # spack -e . develop --path=$(pwd) local.palace@git."${{ github.head_ref || github.ref_name }}"=develop
+        # spack -e . develop --path=$(pwd) palace@git."${{ github.head_ref || github.ref_name }}"=develop
+
+      - uses: julia-actions/setup-julia@v2
+        if: needs.filter.outputs.test == 'true'
+        with:
+          version: '1'
+
+      - uses: julia-actions/cache@v2
+        if: needs.filter.outputs.test == 'true'
 
       - name: Build and deploy
         env:
